# Site settings
name: Mabel Escobar
title: Mabel Escobar| Data Engineer
description: experiences
url: https://yuryescobar.github.io/
baseurl: ''
email: yuryescobar@gmail.com
cover: https://yuryescobar.github.io/img/og.png
logo: https://yuryescobar.github.io/img/emojis/technologist.png
resume: https://yuryescobar.github.io/resume.pdf
social:
  - title: email
    url: mailto:yuryescobar@gmail.com
  - title: twitter
    url: https://twitter.com/yuryescobar
  - title: instagram
    url: https://instagram.com/yuryescobar
  - title: codepen
    url: http://codepen.io/yuryescobar
  - title: github
    url: https://github.com/yuryescobar
  - title: linkedin
    url: https://www.linkedin.com/in/yuryescobar

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
